# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Template

# Model Form Field configuration
form: $/crydesign/wiki/models/template/group_fields.yaml

# Model Class name
modelClass: Crydesign\Wiki\Models\Template

# Default redirect location
defaultRedirect: crydesign/wiki/templates

# Create page
create:
    title: Create Template
    redirect: crydesign/wiki/templates/update/:id
    redirectClose: crydesign/wiki/templates

# Update page
update:
    title: Edit Template
    redirect: crydesign/wiki/templates
    redirectClose: crydesign/wiki/templates

# Preview page
preview:
    title: Preview Template
